spring:
  application:
    name: ms-customer-business
  profiles:
    active: prod
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka