openapi: 3.0.1
info:
  title: Customer API
  description: API para gestionar clientes y sus productos asociados
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /api/customers:
    get:
      summary: Listar todos los clientes
      operationId: getAllCustomers
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerResponse'
    post:
      summary: Crear un cliente
      operationId: createCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerCreateRequest'
      responses:
        '201':
          description: Cliente creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'

  /api/customers/{id}:
    get:
      summary: Obtener cliente por ID
      operationId: getCustomerById
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
    put:
      summary: Actualizar cliente
      operationId: updateCustomer
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerUpdateRequest'
      responses:
        '200':
          description: Cliente actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
    delete:
      summary: Eliminar cliente
      operationId: deleteCustomer
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Cliente eliminado
  /api/customers/{id}/products:
    get:
      summary: Listar productos por id de un cliente
      operationId: getCustomerProducts
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Lista de productos del cliente por id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
    post:
      summary: Agrega un producto a un cliente
      operationId: addProductToCustomer
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '204':
          description: Producto agregado al cliente
  /api/customers/{id}/products/{productId}:
    delete:
      summary: Elimina un producto de un cliente
      operationId: removeProductFromCustomer
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
        - in: path
          name: productId
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Producto eliminado del cliente
  /api/reports/products:
    get:
      summary: Generar reporte de productos por rango de fechas
      operationId: getProductReports
      parameters:
        - in: query
          name: from
          schema:
            type: string
            format: date
          required: true
        - in: query
          name: to
          schema:
            type: string
            format: date
          required: true
      responses:
        '200':
          description: Reporte de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductReportResponse'
  /api/customers/{id}/payments:
    post:
      summary: Pago de productos de crédito de terceros
      operationId: payCreditProduct
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: Resultado del pago
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
  /api/customers/{id}/debit-cards/associate:
    post:
      summary: Asociar tarjeta de débito a cuentas
      operationId: associateDebitCard
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DebitCardAssociationRequest'
      responses:
        '200':
          description: Asociación realizada
          content:
            application/json:
              schema:
                type: string
  /api/customers/{id}/debit-cards/{cardId}/balance:
    get:
      summary: Consultar saldo de cuenta principal asociada a tarjeta de débito
      operationId: getMainAccountBalance
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
        - in: path
          name: cardId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Saldo de cuenta principal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebitCardBalanceResponse'
components:
  schemas:
    CustomerCreateRequest:
      type: object
      properties:
        customerType:
          type: string
          enum: [PERSONAL, BUSINESS]
        profile:
          type: string
          enum: [STANDARD, VIP, PYME]
          description: Perfil del cliente, por defecto STANDARD.
        firstName:
          type: string
        lastName:
          type: string
        businessName:
          type: string
        dni:
          type: string
        ruc:
          type: string
        address:
          type: string
        phone:
          type: string
        email:
          type: string

    CustomerResponse:
      type: object
      properties:
        id:
          type: string
        customerType:
          type: string
          enum: [PERSONAL, BUSINESS]
        profile:
          type: string
          enum: [STANDARD, VIP, PYME]
        firstName:
          type: string
        lastName:
          type: string
        businessName:
          type: string
        dni:
          type: string
        ruc:
          type: string
        address:
          type: string
        phone:
          type: string
        email:
          type: string

    CustomerUpdateRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        businessName:
          type: string
        address:
          type: string
        phone:
          type: string
        email:
          type: string

    ProductRequest:
      type: object
      properties:
        customerId:
          type: string
        category:
          type: string
          enum: [LIABILITY, ASSET]
        type:
          type: string
          enum: [ACCOUNT, LOAN, CREDIT_CARD]
        subType:
          type: string
          enum: [SAVINGS, CURRENT, FIXED_TERM, PERSONAL_LOAN, BUSINESS_LOAN, CREDIT_CARD]

    ProductResponse:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        category:
          type: string
          enum: [LIABILITY, ASSET]
        type:
          type: string
          enum: [ACCOUNT, LOAN, CREDIT_CARD]
        subType:
          type: string
          enum: [SAVINGS, CURRENT, FIXED_TERM, PERSONAL_LOAN, BUSINESS_LOAN, CREDIT_CARD]

    ProductIdRequest:
      type: object
      required:
        - productId
      properties:
        productId:
          type: string

    ProductReportResponse:
      type: object
      properties:
        productId:
          type: string
        type:
          type: string
        subType:
          type: string
        balance:
          type: number
          format: double
        transactions:
          type: array
          items:
            type: string

    PaymentRequest:
      type: object
      properties:
        targetProductId:
          type: string
        amount:
          type: number
          format: double

    PaymentResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string

    DebitCardAssociationRequest:
      type: object
      properties:
        cardId:
          type: string
        accountIds:
          type: array
          items:
            type: string

    DebitCardBalanceResponse:
      type: object
      properties:
        cardId:
          type: string
        productId:
          type: string
        balance:
          type: number
          format: double